const { chromium, expect } = require('@playwright/test');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs');

(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const artifacts = path.join(__dirname, '..', 'artifacts');
  fs.mkdirSync(artifacts, { recursive: true });
  try {
    await page.goto(pathToFileURL(path.join(__dirname, '..', 'preview', 'index.html')).href);
    await expect(page.getByRole('heading', { name: 'Calendário de semanas' })).toBeVisible();
    await expect(page.locator('.cal-row')).toHaveCount(12);
    await expect(page.locator('#kind-filter option')).toHaveText(['Todos', 'Casas', 'Flats']);
    await page.getByLabel('Tipo de acomodação').selectOption({ label: 'Casas' });
    await expect(page.locator('.cal-row')).toHaveCount(8);
    await page.getByLabel('Tipo de acomodação').selectOption({ label: 'Flats' });
    await expect(page.locator('.cal-row')).toHaveCount(4);
    await page.getByLabel('Tipo de acomodação').selectOption('');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await expect(page.locator('#nav .duotone')).toHaveCount(0);
    await page.getByLabel('Tipo de acomodação').selectOption({ label: 'Casas' });
    await page.getByRole('button', { name: 'Ampliar calendário' }).click();
    await expect(page.locator('.sidebar')).toBeHidden();
    await expect(page.locator('.summary')).toBeHidden();
    await expect(page.locator('#kind-filter')).toHaveValue('Casa');
    await expect(page.locator('.cal-row')).toHaveCount(8);
    expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight)).toBe(true);
    await page.screenshot({ path: path.join(artifacts, 'calendar-focused.png'), animations: 'disabled' });
    await page.locator('.week.available').first().click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.locator('.sidebar')).toBeHidden();
    await page.keyboard.press('Escape');
    await expect(page.locator('.sidebar')).toBeVisible();
    await expect(page.locator('#kind-filter')).toHaveValue('Casa');
    await page.getByLabel('Tipo de acomodação').selectOption('');
    await page.getByRole('button', { name: 'Explorar ícones e movimento' }).click();
    await page.getByRole('button', { name: 'Experimentar Phosphor · Duotone' }).click();
    await expect(page.locator('#nav .duotone')).toHaveCount(4);
    await page.getByRole('button', { name: 'Experimentar Lucide · Linear' }).click();
    await expect(page.locator('#nav .duotone')).toHaveCount(0);
    await page.screenshot({ path: path.join(artifacts, 'visual-explorer.png'), animations: 'disabled' });
    await page.getByLabel('Ativar animações curtas').uncheck();
    await expect(page.locator('.drawer')).toHaveCSS('animation-name', 'none');
    await page.getByLabel('Ativar animações curtas').check();
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await expect(page.locator('.drawer')).toHaveCSS('animation-name', 'none');
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    await page.keyboard.press('Escape');
    await page.screenshot({ path: path.join(artifacts, 'calendar.png'), fullPage: true });
    await page.getByLabel('Somente disponíveis').check();
    await expect(page.locator('.week:not(.available)')).toHaveCount(0);
    await page.getByLabel('Somente disponíveis').uncheck();
    await page.getByLabel('Buscar unidade ou titular').fill('impossivel');
    await expect(page.getByText('Nenhuma semana corresponde aos filtros.')).toBeVisible();
    await page.getByLabel('Buscar unidade ou titular').fill('');
    await page.locator('.week.available').first().click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.screenshot({ path: path.join(artifacts, 'week-drawer.png') });
    await page.keyboard.press('Escape');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByLabel('Situação', { exact: true }).selectOption('blocked');
    await page.locator('[data-nav="bank"]').first().click();
    await expect(page.getByRole('heading', { name: 'Banco de semanas', exact: true })).toBeVisible();
    await expect(page.locator('.week')).toHaveCount(15);
    await expect(page.locator('.week:not(.available)')).toHaveCount(0);
    await expect(page.locator('#unit-filter option')).toHaveCount(13);
    await page.getByLabel('Unidade', { exact: true }).selectOption({ label: 'Casa 01' });
    await expect(page.locator('.unit strong')).toHaveText(['Casa 01']);
    await expect(page.locator('.week')).toHaveCount(1);
    await page.getByLabel('Tipo de acomodação').selectOption({ label: 'Flats' });
    await expect(page.getByLabel('Unidade', { exact: true })).toHaveValue('');
    await expect(page.locator('#unit-filter option')).toHaveText(['Todas as unidades', 'Flat 01', 'Flat 02', 'Flat 03', 'Flat 04']);
    await page.getByLabel('Unidade', { exact: true }).selectOption({ label: 'Flat 01' });
    await expect(page.locator('.unit strong')).toHaveText(['Flat 01']);
    await expect(page.locator('.week')).toHaveCount(2);
    await page.locator('[data-nav="calendar"]').first().click();
    await page.locator('[data-nav="bank"]').first().click();
    await expect(page.getByLabel('Unidade', { exact: true })).toHaveValue('9');
    await page.getByLabel('Tipo de acomodação').selectOption({ label: 'Casas' });
    await expect(page.locator('#unit-filter option')).toHaveCount(9);
    await expect(page.getByLabel('Unidade', { exact: true })).toHaveValue('');
    await page.getByLabel('Unidade', { exact: true }).selectOption({ label: 'Casa 02' });
    await expect(page.getByText('Nenhuma semana corresponde aos filtros.')).toBeVisible();
    await page.getByLabel('Unidade', { exact: true }).selectOption('');
    await page.getByLabel('Tipo de acomodação').selectOption('');
    await page.getByLabel('Buscar unidade ou titular de origem').fill('Bruno');
    await expect(page.locator('.week')).toHaveCount(2);
    await page.getByLabel('Tipologia', { exact: true }).selectOption('A');
    await expect(page.getByText('Nenhuma semana corresponde aos filtros.')).toBeVisible();
    await page.getByLabel('Tipologia', { exact: true }).selectOption('');
    await page.getByLabel('Tipo de acomodação').selectOption({ label: 'Casas' });
    await expect(page.locator('.week')).toHaveCount(0);
    await page.getByLabel('Tipo de acomodação').selectOption({ label: 'Flats' });
    await expect(page.locator('.week')).toHaveCount(2);
    await page.locator('[data-week="SEM-223"]').click();
    await expect(page.getByRole('heading', { name: 'Pedidos compatíveis (2)' })).toBeVisible();
    await page.keyboard.press('Escape');
    await page.getByLabel('Buscar unidade ou titular de origem').fill('');
    await page.getByLabel('Tipo de acomodação').selectOption('');
    await page.getByRole('button', { name: 'Mês anterior' }).click();
    await expect(page.locator('.week')).toHaveCount(0);
    await page.getByRole('button', { name: 'Próximo mês' }).click();
    await expect(page.locator('.week')).toHaveCount(15);
    await page.getByRole('button', { name: 'Ampliar calendário' }).click();
    await expect(page.locator('.calendar-focus-title')).toHaveText('Banco de semanas');
    await expect(page.locator('.sidebar')).toBeHidden();
    await page.screenshot({ path: path.join(artifacts, 'bank-calendar.png'), animations: 'disabled' });
    await page.keyboard.press('Escape');
    await page.locator('[data-nav="calendar"]').first().click();
    await expect(page.getByLabel('Situação', { exact: true })).toHaveValue('blocked');
    await page.getByLabel('Situação', { exact: true }).selectOption('');
    await page.locator('[data-nav="requests"]').first().click();
    await page.locator('[data-request="TR-0088"]').click();
    await expect(page.getByRole('button', { name: 'Reservar', exact: true })).toBeDisabled();
    await page.getByRole('button', { name: 'Voltar aos pedidos' }).click();
    await page.locator('[data-request="TR-0087"]').click();
    await page.getByRole('button', { name: 'Reservar', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Revisar e confirmar' })).toBeDisabled();
    await page.getByRole('button', { name: 'Registrar contato e verificar 90 dias' }).click();
    await page.getByLabel('Anexar aceite de WhatsApp').setInputFiles({ name: 'aceite-demo.png', mimeType: 'image/png', buffer: Buffer.from('preview-only') });
    await page.screenshot({ path: path.join(artifacts, 'negotiation.png'), fullPage: true });
    await page.getByRole('button', { name: 'Revisar e confirmar' }).click();
    await page.screenshot({ path: path.join(artifacts, 'confirmation.png') });
    await page.getByRole('button', { name: 'Confirmar troca', exact: true }).click();
    await expect(page.getByText('Troca concluída na demonstração.', { exact: false })).toBeVisible();
    const state = await page.evaluate(() => ({ origin: getWeek(requests[0].origin), target: getWeek(requests[0].target) }));
    expect(state.origin.state).toBe('available');
    expect(state.target.state).toBe('use');
    expect(state.target.owner).toBe('João Pedro');
    expect(state.target.original).toBe(false);
    await page.locator('[data-nav="bank"]').first().click();
    await expect(page.locator(`[data-week="${state.origin.id}"]`)).toHaveCount(1);
    await expect(page.locator(`[data-week="${state.target.id}"]`)).toHaveCount(0);
    await page.locator('[data-nav="requests"]').first().click();
    await page.locator('[data-request="TR-0087"]').click();
    await page.getByRole('button', { name: 'Voltar aos pedidos' }).click();
    await page.locator('[data-request="TR-0082"]').click();
    await expect(page.getByText('48h encerradas — ação do operador necessária')).toBeVisible();
    await page.getByRole('button', { name: 'Liberar reserva', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Liberar reserva' }).click();
    const released = await page.evaluate(() => requests.find(r => r.id === 'TR-0082'));
    expect(released.target).toBeNull();
    expect(released.created).toBe('2026-09-08');
    await page.locator('[data-nav="calendar"]').first().click();
    await page.getByRole('button', { name: 'Novo pedido de troca' }).click();
    await page.locator('select[name="origin"]').selectOption({ index: 1 });
    await page.locator('input[name="desired"]').fill('2027-04-05');
    await page.getByRole('button', { name: 'Criar pedido e buscar opções' }).click();
    await expect(page.getByText('Escolha uma quinta-feira (casa) ou sexta-feira (flat).')).toBeVisible();
    await page.locator('input[name="desired"]').fill('2027-04-16');
    await page.getByRole('button', { name: 'Criar pedido e buscar opções' }).click();
    await expect(page.getByRole('heading', { name: /TR-0089/ })).toBeVisible();
    await page.locator('[data-nav="calendar"]').first().click();
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.getByRole('heading', { name: 'Calendário de semanas' })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: path.join(artifacts, 'mobile.png'), fullPage: true });
    await page.getByRole('button', { name: 'Ampliar calendário' }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight)).toBe(true);
    await page.screenshot({ path: path.join(artifacts, 'calendar-focused-mobile.png'), animations: 'disabled' });
    await page.getByRole('button', { name: 'Voltar à visão normal' }).click();
    await expect(page.locator('.sidebar')).toBeVisible();
    expect(errors).toEqual([]);
    console.log('PASS: calendário, filtros, drawer, prioridade, reserva, aceite, confirmação, liberação manual, criação de pedido, mobile e console.');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
